# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:
- template: ../../config-infra-prod.yml
- name: endpoint_name
  value: taxi-online-$(namespace)$(postfix)$(environment)
- name: endpoint_type
  value: online

# This sets up the optional triggers for the running the pipeline.
# Note: This pipeline is triggered by a manual trigger.
#       This is to avoid running the pipeline when the pipeline is updated.
#
#       See the documentation for more information.
#       https://learn.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops
trigger:
- none

# This the image that is used to run the pipeline
# Note: This is the image that is used to run the pipeline.
#       The image is a Ubuntu 20.04 image.
#
#       See the documentation for more information.
#       https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml
pool:
  vmImage: ubuntu-20.04


stages:
- stage: CreateOnlineEndpoint
  displayName: Create/Update Online Endpoint
  jobs:
    - job: DeployOnlineEndpoint
      steps:
      - checkout: self
        path: s/
        # Install the Azure CLI
        # Note: All pipelines need the ML extension to the Azure CLI. We start with installing the AZ CLI.
        #
        #       See the documentation for more information.
        #       https://learn.microsoft.com/en-us/cli/azure/install-azure-cli
      - template: /aml-cli-v2/install-az-cli.yml

        # Install the Azure ML CLI
        # Note: The step uses Azure CLI to install the Azure ML CLI.
        #
        #       See the documentation for more information.
        #       https://learn.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli?tabs=public
      - template: /aml-cli-v2/install-aml-cli.yml


        # Connect to the Azure ML workspace
        # Note: The steps configures the default workspace and resourcse group for the Azure ML CLI.
        #       Rather than pass the workspace name and resource group name to each command,
        #       the workspace is set as the default workspace.
        #       The step uses Azure ML CLI to connect to the workspace.
        #
        #       See the documentation for more information.
        #       https://learn.microsoft.com/en-us/azure/machine-learning/how-to-manage-environments-v2?tabs=cli#connect-to-the-workspace
      - template: /aml-cli-v2/connect-to-workspace.yml

        # Create the online endpoint
        # Note: The step uses Azure ML CLI to create the online endpoint.
        #
        #       See the documentation for more information.
        #       https://learn.microsoft.com/en-us/azure/machine-learning/how-to-deploy-and-where?tabs=python#create-an-endpoint
      - template: /aml-cli-v2/create-endpoint.yml
        parameters:
          endpoint_file: mlops/azureml/deploy/online/online-endpoint.yml

        # Create the online deployment
        # Note: The step uses Azure ML CLI to create the online deployment.
        #
        #       See the documentation for more information.
        #       https://learn.microsoft.com/en-us/azure/machine-learning/how-to-deploy-and-where?tabs=python#create-a-deployment
      - template: /aml-cli-v2/create-deployment.yml
        parameters:
          deployment_name: taxi-online-dp
          deployment_file: mlops/azureml/deploy/online/online-deployment.yml

        # Allocate traffic to the online deployment
        # Note: The step uses Azure ML CLI to allocate traffic to the online deployment.
        #       You can do the checks on the deployment before allocating traffic to the deployment.
        #       Option: You can allocate a small portion of the traffic to the deployment after the
        #         deployment is tested.
        #       Option: You can also mirror the traffic to the deployment while still working with a
        #         working deployment.
        #
        #       See the documentation on safe deployments for more ideas.
        #       https://learn.microsoft.com/en-us/azure/machine-learning/how-to-safely-rollout-online-endpoints?tabs=azure-cli
      - template: /aml-cli-v2/allocate-traffic.yml
        parameters:
          traffic_allocation: taxi-online-dp=100

        # Test the online deployment
        # Note: he step uses Azure ML CLI to test the online deployment.
        #
      - template: /aml-cli-v2/test-deployment.yml
        parameters:
          deployment_name: taxi-online-dp
          sample_request: data/taxi-request.json
          request_type: json
