# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.


parameters: 
- name: rg_name
  type: string
  default: $(resource_group)
- name: ws_name
  type: string
  default: $(aml_workspace)

steps:
  - task: AzureCLI@2
    displayName: Connect to AML Workspace using CLI v2
    inputs:
      azureSubscription: $(ado_service_connection_aml_ws)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az configure --defaults group=${{ parameters.rg_name }} workspace=${{ parameters.ws_name }}