# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
  - name: registry_name
    type: string
    default: $(registry_name)
  - name: rg_name
    type: string
    default: $(resource_group)
  - name: registry_file
    type: string


steps:
  - task: AzureCLI@2
    displayName: 'Create Registry'
    inputs:
      azureSubscription: '$(ado_service_connection_rg)'
      scriptType: 'bash'
      workingDirectory: $(System.DefaultWorkingDirectory)
      scriptLocation: 'inlineScript'
      inlineScript: |
        set -e
        REG_NAME=$(az ml registry show --name ${{ parameters.registry_name }} -g ${{ parameters.rg_name }} --query name -o tsv  | tr -d '"\r')

        if [[ $REG_NAME == "${{ parameters.registry_name }}" ]];
        then
            echo "Registry ${{ parameters.registry_name }} does exist"
        else 
            echo "Creating registry with parameters  -f ${{ parameters.registry_file }} -g ${{ parameters.rg_name }}"
            az ml registry create  -f ${{ parameters.registry_file }} -g ${{ parameters.rg_name }} --set name=${{ parameters.registry_name }}
        fi
      
      
      